### ISSUE TITLE
エラー画面整形gemの導入

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#15]
## 概要
エラーを見やすくしましょ〜
- gem 'better_errors' をインストールする
- gem 'binding_of_caller' をインストールする

## 注意点
- Gemfileのgroupに気を付けて書く！

## タスク
- [ ] gem 'better_errors' をインストールする
- [ ] gem 'binding_of_caller' をインストールする

**Comment by yoshihiro-hy** [comment]
#31 mergeしました
