### ISSUE TITLE
rails new + 初期設定する

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#16]
## 概要
- オプションに気をつけながら`rails new`しましょ〜。
- ジェネレータの設定
  これです↓
  ```ruby
    class Application < Rails::Application
      ...（省略）
      config.generators do |g|
        g.stylesheets false
        g.javascripts false
        g.helper false
        g.test_framework false
      end
    end
  ```
- `.gitignore` も確認して適宜書き換えましょう。
  - `vendor/bundle`とか`node_modules`とか省きたいですね。

## 注意点
- `rails new`, `.gitignore`の書き換え、ジェネレータファイルの書き換え、でそれぞれコミットを分けるように！

## タスク
- [x] `rails new`する
- [x] ジェネレータの設定
- [x] 試しに`rails g`コマンドしてみて使わないファイルが生成されていないか確認
- [x] `.gitignore`を書き換える
- [x] コミット量が膨大になっていないか、不要なファイルをコミットしていないか確認

**Comment by mayuyuyuyunn** [comment]
$ bundle exec git checkout -b 'rails_new'
→作業をするためにブランチを切り替える。毎度忘れないように！
$ rbenv install --list
→インストールされているrubyのバージョンを確認
$ rbenv local 3.1.2
→ローカルでrubyのバージョンを指定
$ bundle init
→現在の作業ディレクトリ内に、Gemfileを生成
$ bundle exec rails new . --skip-test
→テストをスキップしてrails new(Rspecを使うからスキップ)
$ git status
→生成されたファイルを確認
$ git add .
→全てのファイルを追加する場合は余計なファイルをステージしてないか確認する
$ git commit -m 'Add: rails new . --skip-test #16'
→コミットメッセージは最後に＃githubのイシューの数字をつけると連携されて便利
$ git push -n
→リモートリポジトリにドライプッシュ。サジェストが出てくるのでコピペ。
$ git push --set-upstream origin rails-new
→サジェスト通りにプッシュ
(ここからはGithubにてプルリクを作成する)
$ git checkout main
→ブランチをmainに切り替え
$ git pull
→プルリク通った変更をmainに取り込む

無事にrails new完了！
