### ISSUE TITLE
本番環境(fly.io)で施設詳細が切り替わらない問題を修正する

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#169]
## 概要

本番環境で施設詳細が切り替わらない問題を修正する。
開発環境では動いているため、本番環境特有の問題？

スクロールはjsで扱っているが動いているため、jsは動いている。
ページネーションも動くので、Turboも問題なさそう？

## 本番環境
施設名をクリックしてスクロールするが、詳細部分が切り替わらない。

[![Image from Gyazo](https://i.gyazo.com/d8026ec55c0e1a8005f6e5fe78b08088.gif)](https://gyazo.com/d8026ec55c0e1a8005f6e5fe78b08088)

## 理想の動き(開発環境)
施設名をクリックしてスクロールし、詳細部分が切り替わる。

<a href="https://gyazo.com/1c70af63d87a50d80234193e17b99ad5"><img src="https://i.gyazo.com/1c70af63d87a50d80234193e17b99ad5.gif" alt="Image from Gyazo" width="352"/></a>

## 該当のソースコード

https://github.com/Pluspo/pluspo/blob/eca60c64dce8187f641e8d7b25846aec1e8c043f/app/views/places/index.html.slim#L1-L16

https://github.com/Pluspo/pluspo/blob/eca60c64dce8187f641e8d7b25846aec1e8c043f/app/views/places/_place.html.slim#L1-L35

https://github.com/Pluspo/pluspo/blob/eca60c64dce8187f641e8d7b25846aec1e8c043f/app/views/places/_place_table.html.slim#L1-L14

## 考えられる原因
- jsコンソールでwarningが出ているせい？
```
The resource https://pluspo.fly.dev/assets/application-987995328bcb22eb7af19bfe6c0906ce0ffd0a6d4137dd25c4d0c77a60256e46.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
<a href="https://gyazo.com/86818d547a5523d1399a224da740c6e1"><img src="https://i.gyazo.com/86818d547a5523d1399a224da740c6e1.png" alt="Image from Gyazo" width="363"/></a>

**Comment by betachelsea** [comment]
@yoshiki105 
Slackのほうでもやりとりありがとうございました。要因に近いことが確認できたため共有します。
本番環境のURLですが、上記スクリーンショットにも表記されていましたね。把握が遅くなってしまい、申し訳ございません。
また、Slack上でいくつか仮説を共有しましたが、一旦は下記のように結論付けましたのでお知らせします。

開発(localhost)と本番(fly.io)で問題があるとのことで、挙動を確認したところ、
本番のほうでのみ、必ず `/places` へリダイレクトされるようになっているようです。

例えば、https://pluspo.fly.dev/places?id=2 へアクセスしたとき、リダイレクトが発生し、表示されるURLは https://pluspo.fly.dev/places/ になっているようです。このとき、hotwire側で読み込まれるデータを取る先はリダイレクト後の `/places` になってしまいます。この場合、 `?id=2` のクエリが失われているため、IDに値が入っていない状態です。
IDに値が入っていない場合、PlacesControllerの `set_place` メソッドにより、 id=1 のデータが採用されて表示されます。そのため、ずっと `/places/1.jpg` が表示されたままになってしまっていると思われます。

https://github.com/Pluspo/pluspo/blob/06abaf45260f880a0f1c2bf15b81b39de913d43b/app/controllers/places_controller.rb#L11-L14

一方、開発(localhost)では、http://localhost:3000/places?id=2 へアクセスしても、リダイレクトされずに ちゃんと
 http://localhost:3000/places?id=2 が表示できているようです。そのため、正常に動きます。

自分がfly.ioの利用の経験がないのですが、`/places` ページへのリダイレクトについて、お心当たりのある設定はございますか？

**Comment by yoshiki105** [comment]
@betachelsea 
ありがとうございます！
開発環境、本番環境それぞれで`places?id=4`リンクを踏んだ時の挙動を以下のように確認できました。

- 開発環境
<a href="https://gyazo.com/8a6f81c95c26ef49410dbb93aced39d7"><img src="https://i.gyazo.com/8a6f81c95c26ef49410dbb93aced39d7.png" alt="Image from Gyazo" width="1196"/></a>

- 本番環境
<a href="https://gyazo.com/051ea1f49233e6dfbb2ddbe6255c4f28"><img src="https://i.gyazo.com/051ea1f49233e6dfbb2ddbe6255c4f28.png" alt="Image from Gyazo" width="1336"/></a>

本番環境では`places?id=4`のリンクが`301 fetch /Redirect`となっていますがこれのせいということでしょうか。。
特にfly.ioの設定等はいじっていないため、心当たりはないですが、調べてみます！

**Comment by yoshiki105** [comment]
Railsのサーバーログは以下のようになっていました。（不要な部分は省略しています）

- 開発環境
```
Started GET "/places?id=4" for ::1 at 2023-03-02 08:37:08 +0900
Processing by PlacesController#index as HTML
  Parameters: {"id"=>"4"}
  Place Load (0.1ms)  SELECT "places".* FROM "places" WHERE "places"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
  ↳ app/controllers/places_controller.rb:13:in `set_place'
  Rendering places/index.html.slim
  SQL (4.9ms) （略）
  ↳ app/views/places/_place_table.html.slim:12
  Rendered collection of schedules/_schedule.html.slim [20 times] (Duration: 21.2ms | Allocations: 22317)
  Schedule Count (1.1ms)  (略）
  ↳ app/views/places/_place_table.html.slim:14
  Rendered places/_place_table.html.slim (Duration: 43.3ms | Allocations: 34016)
  Rendered places/_place.html.slim (Duration: 3.9ms | Allocations: 2971)
  Rendered places/index.html.slim (Duration: 47.6ms | Allocations: 37193)
Completed 200 OK in 51ms (Views: 42.1ms | ActiveRecord: 6.1ms | Allocations: 38254)
```

- 本番環境
```
Started GET "/places/" for 2a09:8280:1::3:e48d at 2023-03-01 23:51:09 +0000
Processing by PlacesController#index as HTML
Rendered places/index.html.slim (Duration: 24.4ms | Allocations: 11104)
Completed 200 OK in 28ms (Views: 15.4ms | ActiveRecord: 10.6ms | Allocations: 11669)
```

- 考察
本番環境の方ではリクエストが`/places/`になっているため、`/places?id=4`というリクエストがそもそもRailsに届いていないっぽいですね。。

本番環境の挙動として
1. `places?id=4`のリクエストをTurboが`fetch /Redirect`として処理する
2. Turboからの`/places/`というリクエストをRailsが受け取る
3. クエリなしなので`set_place`で`id=1`が代入される

ということでしょうか。

- 本番環境でのTurboの挙動
- 本番環境でのFly.ioの挙動

あたりについて調べてみます！

**Comment by betachelsea** [comment]
サーバーログありがとうございます。考察いただいた通り、Railsがそもそも `/places?id=4` にアクセスされたことを知らない状態、というのが不具合の根幹かと思います。

お心当たりがないとのことで、仮の回避策の提案ですが、ルーティングが現在 `/places?id=4` など id をクエリパラメータとして渡すようになっていますが、こちら  `/places/2` のようにpathに含んでしまう形にするのはいかがでしょうか。

https://github.com/Pluspo/pluspo/blob/9c0de9002b344b50d529a6a5dced5bfebea1875e/app/views/schedules/_schedule.html.slim#L6

↑の部分の `places_path(id: schedule.place.id)` とありますが、こちらを `place_path(schedule.place)` とするイメージです。すでに PlacesController#show へのルーティングと実装はあるようなので、動作するかと思います。通常だとページ遷移が発生してしまいますが、Turboを利用しているため、呼び出された情報は下部の地図画面にのみ反映されるのではと考えております。

本番URLの挙動をさらに確認したところ、例えば利用規約 https://pluspo.fly.dev/terms はリダイレクトされずに閲覧できるので、リダイレクトの対象はクエリパラメータ( `?id=X` の部分 )のみではないか、と仮説を立てました。もし仮説があっていれば、ルーティングの工夫で一旦問題は解決するかと思われます。ただし、もし上記方法で解決したとしても、クエリパラメータがリダイレクトされるという問題は引き続き発生しているため、ご留意いただきたいです。

もしリダイレクトの問題に解消見込みがない場合は、一度上記お試しいただけますと幸いです。あくまで仮説でして、本番環境でのみしか発生しない問題とのことで、確実性の高いご提案ができず、申し訳ございません。
よろしくお願いいたします。

**Comment by yoshiki105** [comment]
ご提案ありがとうございます！
そちらの変更で試してみましたが、URLが`/places.1`のようにドットで繋がってしまい、上手くいきませんでした。。
コントローラ内の`params[:id] ||= 1`をコメントアウトしましたが、`places/index.html.slim`内に`@place`があるためエラーになってしまいました。ちょっと設計が悪そうですね。。すみません。
