### ISSUE TITLE
FirstStage資料作成

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#17]
## 概要
9/18のFirstStageで使用する資料の作成です。
締め切りは9/1 23:59です！！！！
[詳細](https://bornrex.notion.site/First-Stage-f78c25c84a594cf381d891ba7d710af6)

- 概要シートの作成
- プレゼン資料シートの作成

## タスク
- [ ] 概要シートの作成
- [ ] プレゼン資料シートの作成
- [ ] 各シートの応募

**Comment by yoshiki105** [comment]
概要シートと発表スライドとりあえずNotionにまとめてあるので、お願いします！

**Comment by mayuyuyuyunn** [comment]
スライドと発表用資料ノーションに貼っておきました。適宜確認の上修正お願いします。
