### ISSUE TITLE
CSSフレームワークの検討・導入

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#28]
## 概要

CSSフレームワークの導入
TailwindとTailwindのフレームワークdaisyUIをインストール

## 参考資料・スクショなど

[参考記事](https://zenn.dev/yoiyoicho/articles/410a7e3fd892b5)
[Tailwind](https://tailwindcss.jp/)
[daisyUI](https://daisyui.com/)

## タスク
- [ ] Tailwindインストール
- [ ] daisyUIインストール

**Comment by mayuyuyuyunn** [comment]
Tailwind使ってみたいです！！！！
