### ISSUE TITLE
Githubの通知をDIscordに送る

### ISSUE THREAD

**Issue by mayuyuyuyunn** [Pluspo/pluspo#29]
## 概要
タイトル通り
## 参考資料・スクショなど
[参考記事](https://mekurun.com/tips/discord-github/)
## タスク
- [x] 設定
- [x] 試す
- [x] メンバーを招待する

**Comment by mayuyuyuyunn** [comment]
設定完了しました。Discordの名前がわからなかったので集まれた時に招待します〜！！

**Comment by yoshiki105** [comment]
はいれました！ 🙋‍♂️

**Comment by mayuyuyuyunn** [comment]
全員招待したのでクローズします。
