### ISSUE TITLE
ロゴを考える

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#32]
## 概要
- ロゴどうする！？
- 自分たちで考える or 依頼する
  - 依頼するなら、間に合うように早めがいい
  - Twitterで無料で作ってくれる人も探せばいるかも
  - やすく引き受けてくれる人が複数人いれば、4人で4人に申し込んで、4案の中から選ぶ方法もある
  - 依頼してとんずらされたら詰むから、自分たちでも同時に考える必要がありそう

## タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by yoshiki105** [comment]
ロゴ決めちゃってOKです！！
サイト名は最初大文字で「Pluspo」でお願いします。
ロゴに背景色入る場合は、ヘッダーと同じ色にしないと浮いちゃうので注意。

**Comment by 0417-hub** [comment]
こんな感じのはどうでしょうか！
[![Image from Gyazo](https://i.gyazo.com/aaa115a381993e244f1feabbeae56008.png)](https://gyazo.com/aaa115a381993e244f1feabbeae56008)

[![Image from Gyazo](https://i.gyazo.com/f5c202dabd7de9d976b577fea948eb66.png)](https://gyazo.com/f5c202dabd7de9d976b577fea948eb66)

[![Image from Gyazo](https://i.gyazo.com/827f010035a1c634422c81234e523f22.png)](https://gyazo.com/827f010035a1c634422c81234e523f22)

[![Image from Gyazo](https://i.gyazo.com/03e56b33f4a7f5383b9517a9e06bcc64.png)](https://gyazo.com/03e56b33f4a7f5383b9517a9e06bcc64)

**Comment by yoshiki105** [comment]
サイトの背景とヘッダーの色考えると1が好き。1に1票！

**Comment by 0417-hub** [comment]
概要の下記3点ですが、依頼だと8日に100%間に合わない + ロゴならいつでも変更可能なので、一旦このサイト内で決めましょう！
依頼するなら、間に合うように早めがいい
Twitterで無料で作ってくれる人も探せばいるかも
やすく引き受けてくれる人が複数人いれば、4人で4人に申し込んで、4案の中から選ぶ方法もある

**Comment by yoshihiro-hy** [comment]
上から2番目で！
なんかトイストーリーのロゴにも見えなくは無いですが😅
[![Image from Gyazo](https://i.gyazo.com/99e490cde2952818ab315828dedece97.png)](https://gyazo.com/99e490cde2952818ab315828dedece97)

**Comment by mayuyuyuyunn** [comment]
武藤さん的にはどれがいいですか？
1か4かサブタイトルありバージョンがいいなと思いました（多くてすみません）

**Comment by yoshiki105** [comment]
1にしましょう！！
1のロゴにサブタイトル「生活にsportsをplusする」を追加しましょう！！

**Comment by 0417-hub** [comment]
ロゴの目立ち方とか汎用性考えて自分も1でした！
サブタイトルありバージョンはポカリにしか見えなくなったので！w

**Comment by yoshiki105** [comment]
たしかにポカリですねw

武藤さん今度時間ある時に1のサブタイトル入りバージョンお願いします！！

**Comment by 0417-hub** [comment]
サブタイトルに色あり・なしで追加してみました！

なし
[![Image from Gyazo](https://i.gyazo.com/d68b026c590d1153cdd4a20f4ac1e8a6.png)](https://gyazo.com/d68b026c590d1153cdd4a20f4ac1e8a6)

あり
[![Image from Gyazo](https://i.gyazo.com/6c6507f946a8c9672531dbf4e58c385e.png)](https://gyazo.com/6c6507f946a8c9672531dbf4e58c385e)

**Comment by yoshiki105** [comment]
右の線消してみましたどうですかね？

<img width="577" alt="Pluspoロゴ" src="https://user-images.githubusercontent.com/66538632/188299214-251d3c86-75d4-4872-9764-2a4aef1e72bb.png">

**Comment by 0417-hub** [comment]
あり！！

**Comment by yoshiki105** [comment]
決まり！！！！！！！！！！！

**Comment by yoshiki105** [comment]
現在のロゴはこれだけど、3点気になります！
- 「生活にsportsをPlusする」の`Plus`
  - `plus`の方がいいですかね？どうだろ。
- 黄色い線が左だけ長い...？
  - でもこれはこれでバランスがいいのか...？左だけ長いおかげで`Pluspo`の文字が真ん中に来てるし。。
- スクショで無理やり作ったから画質が、、、 => 高画質のもの欲しいです！笑 @武藤さん

[![Image from Gyazo](https://i.gyazo.com/2c2f7686639147a217e9bee21f690044.png)](https://gyazo.com/2c2f7686639147a217e9bee21f690044)

**Comment by yoshiki105** [comment]
上記ロゴのカラーコードはこちら
- 背景 #eef2e2
- 黄色のライン #f8da5b
- 人・文字 #237291

**Comment by yoshiki105** [comment]
スライドとかで使えるようにサブタイトルなしのバージョンもほしい。
あと、背景透過バージョンも持っておくとよさそう？

**Comment by 0417-hub** [comment]
- 「生活にsportsをPlusする」の`Plus`
   - `Pluspo`が大文字の`P`なので一旦合わせた感じです！
ここに関してはどっちが良いとかはなく単純に見た目の印象、好みかと！

- 黄色い線が左だけ長い...？
   - これも空間を作りたくない(固まった感じ)が好みなら線の長さを合わせた方がいいですが、個人的に違和感は全く感じないですね！

- FSがもう使えないので、なんか良さげなフリーソフト探してみますー

**Comment by yoshiki105** [comment]
てっきりロゴを作ったサイトで編集までできると思っていました…すみません！

元データ持ってますか？自分が貼ったやつは画質荒いと思うので…

**Comment by 0417-hub** [comment]
サブタイトルあり
[![Image from Gyazo](https://i.gyazo.com/4a4bcd47a1b52a649ee3e9a02c21bb87.png)](https://gyazo.com/4a4bcd47a1b52a649ee3e9a02c21bb87)

サブタイトルなし
[![Image from Gyazo](https://i.gyazo.com/479ea761694d172f0767c38ae2f152b8.png)](https://gyazo.com/479ea761694d172f0767c38ae2f152b8)

**Comment by yoshiki105** [comment]
画質OKですあざます！！

サブタイトルのフォントは前の方が見やすいかも？笑
なんかひらがなが読みにくいかなぁ

**Comment by 0417-hub** [comment]
前のフォントはLogoMakerのフォントで、確認しましたがフォント名が不明なのでわからないんです、、、w

**Comment by yoshiki105** [comment]
なるほど！w
なんちゃらゴシックってやつありますかね？たぶん見やすいので、あればそれで！

**Comment by 0417-hub** [comment]
線あり
[![Image from Gyazo](https://i.gyazo.com/85526eb8c57acb1ed3ab497c96c5d800.jpg)](https://gyazo.com/85526eb8c57acb1ed3ab497c96c5d800)

線なし
[![Image from Gyazo](https://i.gyazo.com/c794a54b9ec923c8c3fc8abb2601a3fe.jpg)](https://gyazo.com/c794a54b9ec923c8c3fc8abb2601a3fe)

どうでしょう、、、？

**Comment by yoshiki105** [comment]
上記のもので決定。LGTM！CLOSE！
