### ISSUE TITLE
faviconの設定

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#61]
## 概要
現在デフォルトだけど、ロゴにしたい
[![Image from Gyazo](https://i.gyazo.com/65e3d91f6d6b512250e8444f148f3c55.png)](https://gyazo.com/65e3d91f6d6b512250e8444f148f3c55)

**Comment by yoshiki105** [comment]
編集もできる！
https://www.xiconeditor.com

**Comment by yoshiki105** [comment]
色情報
背景 #eef2e2
黄色のライン #f8da5b
人・文字 #237291

**Comment by mayuyuyuyunn** [comment]
三宅やります〜！！！！

**Comment by mayuyuyuyunn** [comment]
close #61
