### ISSUE TITLE
レスポンシブデザイン適用

### ISSUE THREAD

**Issue by yoshihiro-hy** [Pluspo/pluspo#64]
## 概要
サイト全体をスマホに適応したデザインにする(レスポンシブデザイン)
https://gmotech.jp/semlabo/seo/blog/responsive_design/

## 目的
閲覧ユーザーの画面サイズに合わせることで見やすくしたい
### 現在こんな感じ
[![Image from Gyazo](https://i.gyazo.com/4c1f2b6d53a232eb4821b8810b233112.png)](https://gyazo.com/4c1f2b6d53a232eb4821b8810b233112)

**Comment by yoshiki105** [comment]
スマホ用のレイアウトは考え直す必要がありそうですねー
今のまま左右にわけるとスマホじゃ見づらそうなので、、
