### ISSUE TITLE
施設の横断検索機能(ransack)

### ISSUE THREAD

**Issue by yoshihiro-hy** [Pluspo/pluspo#7]
## 概要

ログインしていないユーザー
- 施設一括検索機能

ログイン済みユーザー
- イベント時間検索

## タスク
- 

- [ ] headerに検索バー作成

**Comment by yoshiki105** [comment]
とりあえずヘッダーに置きましょう。
非同期で検索結果を表示させたいが、難しい場合はまず検索ボタンポチーからの画面遷移でOK
やっぱりransackなのかな？ここも調査必要かも。
