### ISSUE TITLE
東京都の肥満率のデータ取得

### ISSUE THREAD

**Issue by yoshihiro-hy** [Pluspo/pluspo#70]
## 概要
東京都の健康・栄養状況
https://www.fukushihoken.metro.tokyo.lg.jp/kenkou/kenko_zukuri/ei_syo/tomineiyou.files/28gaiyou.pdf
## タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by mayuyuyuyunn** [comment]
原田さんのいたずら
