### ISSUE TITLE
ヘッダーの検索バーで曖昧検索実装

### ISSUE THREAD

**Issue by yoshihiro-hy** [Pluspo/pluspo#71]
## 概要
- ヘッダーの検索バーに曖昧検索機能実装
- スポーツの検索欄はクリックするとプルダウンでスポーツごとのアイコン表示
## 目的
- 曖昧検索を実装することでユーザーの使用感を良くする
## 参考資料・スクショなど
[![Image from Gyazo](https://i.gyazo.com/be7148e14bb219275339c6f8129d0201.png)](https://gyazo.com/be7148e14bb219275339c6f8129d0201)
こんな感じ
## タスク
- [ ] まずノーマルな曖昧検索実装 
- [ ] 追加でスポーツ欄のみアイコン表示させる

**Comment by yoshiki105** [comment]
アイコン表示とりあえず無しで。
