### ISSUE TITLE
スタイル整える（Searchボタン、ページネーション）

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#84]
## 概要

サイトの色味に合わせる

---

- Searchボタン
  
  [![Image from Gyazo](https://i.gyazo.com/8fb58f298009940db7df13524a04fd8a.png)](https://gyazo.com/8fb58f298009940db7df13524a04fd8a)

---

- ページネーション
  - クラス名：`pagination`, `page-item`, `page-item active`, `page-link`
  
  [![Image from Gyazo](https://i.gyazo.com/91435c46dfc84c7a8be56bbebeeba698.png)](https://gyazo.com/91435c46dfc84c7a8be56bbebeeba698)

**Comment by mayuyuyuyunn** [comment]
ページネーションの色変えます
