### ISSUE TITLE
施設のMAP画像の追加

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#85]
# 概要

Googleマップ間に合わなさそうなので、、、

- 施設に写真を入れるためのカラムを追加
- Googleマップで各施設周辺をスクショ
- 施設のseedに上記写真を追加
- viewにそれぞれ表示

**Comment by mayuyuyuyunn** [comment]
https://qiita.com/ofuna/items/5847e73c43991d6e7c5c
