### ISSUE TITLE
イベント一覧画面をキレイにする（スライド用）（figma）

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#90]
## 概要

figmaのこの画面を
  [![Image from Gyazo](https://i.gyazo.com/b60bc9292c52eaf23fd1c4a5ecd19550.png)](https://gyazo.com/b60bc9292c52eaf23fd1c4a5ecd19550)
- 色を検索画面と同じ感じにする
- 実際にありそうなイベントにする
- ここのスライドの左に入れます！
  [![Image from Gyazo](https://i.gyazo.com/48b2f7a101f673aed350d92d161be180.png)](https://gyazo.com/48b2f7a101f673aed350d92d161be180)

**Comment by yoshiki105** [comment]
@0417-hub 
　イベント機能間に合わない
→ プレゼンのため画面だけでも欲しい
→ scaffoldで作るか、figmaで作るか…
→ figmaの方が早い

と思ってのissueですが、たぶんfigmaの方が早いですよね…？
もしscaffoldの方が早く出来そうなら、そっちでも可です！🙆‍♂️

**Comment by 0417-hub** [comment]
@yoshiki105 
これは明日やっちゃいます！

一応確認でfigma内でイベント一覧画面の画像の
・色味調整
・ありそうなイベント複数記載
・イベントの詳細記載
それをスライドに差し込むってことですよね？

1つ心配なのがfigma内のPCサイズの画像のレイアウトのまま(左に一覧/右に詳細)でスライドに差し込めますか？

**Comment by yoshiki105** [comment]
@0417-hub 

> 一応確認でfigma内でイベント一覧画面の画像の
・色味調整
・ありそうなイベント複数記載
・イベントの詳細記載
それをスライドに差し込むってことですよね？

これらを盛り込んだページを1ページ作って、それを差し込むかんじです！

> 1つ心配なのがfigma内のPCサイズの画像のレイアウトのまま(左に一覧/右に詳細)でスライドに差し込めますか？

スライドの余白は調整できるので、気にしなくてokです！

答えになってますかね…？

**Comment by 0417-hub** [comment]
@yoshiki105 
一旦作ってみたんですけどどうでしょうか？
https://www.figma.com/file/n5k0uE9SSgQsBbXuZxMz5o/%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?node-id=0%3A1

**Comment by yoshiki105** [comment]
@0417-hub 
figma上でコメントしました！
全体的なレイアウトはいい感じです！
あとは色調整お願いします！

**Comment by 0417-hub** [comment]
できました！
![image](https://user-images.githubusercontent.com/74312005/195020919-162cdef9-4751-4136-9d66-5938f446d20d.png)
